# Generated by Django 5.0.4 on 2024-04-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_clients_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Método de Pago')),
            ],
            options={
                'verbose_name': 'Metodo de Pago',
                'verbose_name_plural': 'Metodos de Pago',
                'ordering': ['id'],
            },
        ),
    ]
