# Generated by Django 5.0.4 on 2024-06-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_cotizacion_detcotizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detcotizacion',
            name='cotizacion',
        ),
        migrations.RemoveField(
            model_name='detcotizacion',
            name='repl',
        ),
        migrations.DeleteModel(
            name='Cotizacion',
        ),
        migrations.DeleteModel(
            name='DetCotizacion',
        ),
    ]
