# Generated by Django 5.0.4 on 2024-06-13 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, default=0.0, max_digits=9, verbose_name='Precio')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('repl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.replacement', verbose_name='Repuesto(s)')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle Cotización',
                'verbose_name_plural': 'Detalle Cotizaciones',
                'ordering': ['id'],
            },
        ),
    ]
